apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: reactsurvey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "crud_db"
          ports:
            - containerPort: 3306
