apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.3.2 # Phiên bản ổn định mới nhất hiện tại
    helm:
      releaseName: monitoring
      values: |
        grafana:
          adminPassword: admin123
          service:
            type: NodePort

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: NodePort

        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'nguyenvanhuyhoang2609@gmail.com'
              smtp_auth_username: 'nguyenvanhuyhoang2609@gmail.com'
              smtp_auth_password_file: '/etc/alertmanager/secrets/alertmanager-secret/smtp-password'
              smtp_require_tls: true
            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 1m
              repeat_interval: 1h
              receiver: 'email-alert'
            receivers:
            - name: 'null'
            - name: 'email-alert'
              email_configs:
              - to: 'nguyenvanhuyhoang2609@gmail.com'
                send_resolved: true
          alertmanagerSpec:
            secrets:
            - alertmanager-secret

        nodeExporter:
          enabled: false

        kubelet:
          serviceMonitor:
            insecureSkipVerify: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
